name 'jlcox-postgresplus'
version '1.0.1'
author 'Jason Cox'
license 'Apache License, Version 2.0'
source 'git@github.com:jlcox1970/postgresplus.git'
project_page 'https://github.com/jlcox1970/postgresplus'
summary 'Installation and confgiuration of a Postgres Plus server with replication'
description 'This module installs Postgres Plus (EnterpiseDB) and allows for streaming replication to be creted'
